[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme':'wombat',
      \ 'active': {
      \   'right': [ [ 'syntastic', 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component_expand': {
      \   'syntastic': 'SyntasticStatuslineFlag',
      \ },
      \ 'component_type': {
      \   'syntastic': 'error',
      \ }
      \ }
augroup AutoSyntastic
  autocmd!
  autocmd BufWritePost *.c,*.cpp call s:syntastic()
augroup END
function! s:syntastic()
  SyntasticCheck
  call lightline#update()
endfunction
'''

[[plugins]]
repo='thinca/vim-quickrun'
hook_source='''
  let g:quickrun_config={'python':{'command':'python3'}}
'''

[[plugins]]
repo='scrooloose/syntastic'
hook_post_source = ''' 
let g:syntastic_mode_map={ 'mode':'active',
  \ 'active_filetypes':['python']}
'''

[[plugins]]
repo='tell-k/vim-autopep8'

[[plugins]]
repo='hynek/vim-python-pep8-indent'

[[plugins]]
repo='jmcantrell/vim-virtualenv'

[[plugins]]
repo='hachibeeDI/python_hl_lvar.vim'



[[plugins]]
repo='scrooloose/nerdtree'

[[plugins]]
repo='Townk/vim-autoclose'

[[plugins]]
repo='neovim/python-client'

[[plugins]]
repo='davidhalter/jedi'

[[plugins]]
repo='zchee/deoplete-jedi'

[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo='Shougo/context_filetype.vim'

[[plugins]]
repo='ctrlpvim/ctrlp.vim'

[[plugins]]
repo='cespare/vim-toml'
on_ft="toml"

[[plugins]]
repo='kassio/neoterm'

[[plugins]]
repo='airblade/vim-gitgutter'

[[plugins]]
repo='Shougo/denite.nvim'

