[[plugins]] # 補完
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source ='''
	let g:deoplete#enable_at_startup=1
	inoremap <expr><tab> pumvisible()?"\<C-n>":
	\ neosnippet#expandble_or_jumpable() ?
	\ "\<Plug>(neosnippet_expand_or_jump)":"\<tab>"
  
  autocmd FileType python setlocal omnifunc=jedi#completions
  let g:jedi#auto_vim_configuration=0
  if !exists('g:deoplete#force_omni_input_patterns')
    let g:deoplete#force_omni_input_patterns = {}
  endif

  let g:deoplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w`'
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <expr><TAB> neosnippet#expandable_or_jumpable() ? "<Plug>(neosnippet_expand_or_jump)":pumvisible()?"\<C-n>":"\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ? "<Plug>(neosnippet_expand_or_jump)":"\<TAB>"
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
