[[plugins]]
repo = 'shougo/dein.vim'

#[[plugins]] # ステータスライン
#repo = 'itchyny/lightline.vim'
#hook_add = '''
#let g:lightline = {
#      \ 'colorscheme':'wombat',
#      \ 'active': {
#      \   'right': [ [ 'syntastic', 'lineinfo' ],
#      \              [ 'percent' ],
#      \              [ 'fileformat', 'fileencoding', 'filetype' ] ]
#      \ },
#      \ 'component_expand': {
#      \   'syntastic': 'syntasticstatuslineflag',
#      \ },
#      \ 'component_type': {
#      \   'syntastic': 'error',
#      \ }
#      \ }
#augroup autosyntastic
#  autocmd!
#  autocmd bufwritepost *.c,*.cpp call s:syntastic()
#augroup end
#function! s:syntastic()
#  syntasticcheck
#  call lightline#update()
#endfunction
#'''

[[plugins]]
repo='vim-airline/vim-airline'
hook_add='''
let g:airline_powerline_fonts = 1
set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add='''
let g:airline_theme='onedark'
'''

[[plugins]]
repo='thinca/vim-quickrun'
hook_source='''
let g:quickrun_config={'python':{'command':'python3'},'systemverilog':'vlog -sv'}
'''

[[plugins]]
repo='scrooloose/syntastic'
hook_post_source = ''' 
let g:syntastic_mode_map={ 'mode':'active',
\ 'active_filetypes':['python']}
let g:syntastic_cpp_compiler_options='-std=c++14 -Wall'
'''

#[[plugins]]
#repo='tell-k/vim-autopep8'

#[[plugins]]
#repo='hynek/vim-python-pep8-indent'

#[[plugins]]
#repo='jmcantrell/vim-virtualenv'

#[[plugins]]
#repo='hachibeeDI/python_hl_lvar.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides' 
hook_add='''
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#34394e   ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#1e2132 ctermbg=4
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
nmap sc <Plug>NERDCommenterToggle
vmap sc <Plug>NERDCommenterToggle
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add='''
let g:winresizer_keycode_left=97
let g:winresizer_keycode_up=119
let g:winresizer_keycode_down=115
let g:winresizer_keycode_right=100
'''



[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add='''
let g:EasyMotion_do_mapping=0
nmap sx <Plug>(easymotion-s2)
nmap s/ <Plug>(easymotion-sn)
xmap sx <Plug>(easymotion-s2)
xmap s/ <Plug>(easymotion-sn)
'''

[[plugins]]
repo='scrooloose/nerdtree'

[[plugins]]
repo='Townk/vim-autoclose'

[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo='Shougo/context_filetype.vim'

[[plugins]]
repo='ctrlpvim/ctrlp.vim'

[[plugins]]
repo='cespare/vim-toml'
on_ft="toml"

[[plugins]]
repo='kassio/neoterm'

[[plugins]]
repo='airblade/vim-gitgutter'

#[[plugins]]
#repo='Shougo/denite.nvim'

