[[plugins]]
repo='cyansprite/deoplete-omnisharp'
on_ft='cs'
hook_add='''
  let g:OmniSharp_selector_ui = 'ctrlp'  " Use ctrlp.vim
  let g:deoplete_omnisharp_exe_path   = get(g:, "deoplete_omnisharp_exe_path", '~/.cache/dein/repos/github.com/cyansprite/deoplete-omnisharp/omnisharp-server/OmniSharp/bin/Debug/OmniSharp.exe')
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build='make'
on_ft='cs'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft='cs'

[[plugins]]
repo = 'OrangeT/vim-csharp'
on_ft='cs'

