format = """
${custom.pwdbefore}
$username[\uE0B0](fg:#5E35B1 bg:#424242)[ \\$ ](bg:#424242)[\uE0B0](fg:#424242) 
"""

add_newline = false

[username]
style_user = "fg:white bold bg:#5E35B1"
style_root = "black bold"
format = "[ $user ]($style)"
disabled = false
show_always = true

[custom.pwdbefore]
command = "dirname $PWD | sd \"$HOME/\" '' | sd  '((/[^/]+){2})/.+' '$1/...' | sd \"/\" ' \uE0B0 '"
format = "pwd [$output](white bold)"
shell  = ["zsh"]
