historyFile: ~/.config/go-cdx/history
bookmarkFile: ~/.config/go-cdx/bookmark
noOutput: true
make: false
source:
  - name: "ghq list"
    alias: "g"
    skipcolumn: 1
    command: "ghq list|awk -F/ -v X=\"$(ghq root)\" '{print $NF,X\"/\"$0}'|column -t"
fuzzyfinder:
  command: "fzf"
